{ config, pkgs,... }:

{
  home.packages = with pkgs;[
    sbctl
    flatpak
    brave
    alacritty
    vesktop
    telegram-desktop
    fastfetch
    obsidian
    vscode
    cmatrix
    mangohud
    prismlauncher
    cava
    obs-studio
    blanket
    osu-lazer-bin
    protonvpn-gui
    onlyoffice-desktopeditors
    peaclock
    btop
    kdePackages.isoimagewriter
    kdePackages.kcalc
    kdePackages.kcharselect
    kdePackages.kclock
    kdePackages.kcolorchooser
    kdePackages.kolourpaint
    kdePackages.partitionmanager
    kdePackages.kdenlive
    devenv
    blender
    godot
    dnsmasq
    haruna
    video-trimmer
  ];
}
